// GENERATED by tools/make_fold.py from lang/*.txt -- do not edit.
//
// Every character that occurs in any language the game ships, and the
// ASCII a player types to find it. See main/i18n/fold.h for why, and
// run `python3 tools/make_fold.py` after adding a language.
//
// 290 characters; the longest folds to 4.

// A folded form is never longer than this, NUL included.
#define FOLD_REP_MAX 5

typedef struct {
    uint16_t   cp;
    char const rep[FOLD_REP_MAX];
} fold_entry_t;

// Sorted by codepoint: fold_known() and the fold itself binary-search it.
static fold_entry_t const FOLD_TABLE[] = {
    {0x00AB, ""},  // « left-pointing double angle quotation mark
    {0x00B7, ""},  // · middle dot
    {0x00BB, ""},  // » right-pointing double angle quotation mark
    {0x00BF, ""},  // ¿ inverted question mark
    {0x00C0, "a"},  // À latin capital letter a with grave
    {0x00C1, "a"},  // Á latin capital letter a with acute
    {0x00C2, "a"},  // Â latin capital letter a with circumflex
    {0x00C3, "a"},  // Ã latin capital letter a with tilde
    {0x00C4, "a"},  // Ä latin capital letter a with diaeresis
    {0x00C5, "a"},  // Å latin capital letter a with ring above
    {0x00C6, "ae"},  // Æ latin capital letter ae
    {0x00C7, "c"},  // Ç latin capital letter c with cedilla
    {0x00C8, "e"},  // È latin capital letter e with grave
    {0x00C9, "e"},  // É latin capital letter e with acute
    {0x00CA, "e"},  // Ê latin capital letter e with circumflex
    {0x00CB, "e"},  // Ë latin capital letter e with diaeresis
    {0x00CC, "i"},  // Ì latin capital letter i with grave
    {0x00CD, "i"},  // Í latin capital letter i with acute
    {0x00CE, "i"},  // Î latin capital letter i with circumflex
    {0x00D0, "d"},  // Ð latin capital letter eth
    {0x00D1, "n"},  // Ñ latin capital letter n with tilde
    {0x00D2, "o"},  // Ò latin capital letter o with grave
    {0x00D3, "o"},  // Ó latin capital letter o with acute
    {0x00D4, "o"},  // Ô latin capital letter o with circumflex
    {0x00D5, "o"},  // Õ latin capital letter o with tilde
    {0x00D6, "o"},  // Ö latin capital letter o with diaeresis
    {0x00D8, "o"},  // Ø latin capital letter o with stroke
    {0x00D9, "u"},  // Ù latin capital letter u with grave
    {0x00DA, "u"},  // Ú latin capital letter u with acute
    {0x00DB, "u"},  // Û latin capital letter u with circumflex
    {0x00DC, "u"},  // Ü latin capital letter u with diaeresis
    {0x00DD, "y"},  // Ý latin capital letter y with acute
    {0x00DE, "th"},  // Þ latin capital letter thorn
    {0x00DF, "ss"},  // ß latin small letter sharp s
    {0x00E0, "a"},  // à latin small letter a with grave
    {0x00E1, "a"},  // á latin small letter a with acute
    {0x00E2, "a"},  // â latin small letter a with circumflex
    {0x00E3, "a"},  // ã latin small letter a with tilde
    {0x00E4, "a"},  // ä latin small letter a with diaeresis
    {0x00E5, "a"},  // å latin small letter a with ring above
    {0x00E6, "ae"},  // æ latin small letter ae
    {0x00E7, "c"},  // ç latin small letter c with cedilla
    {0x00E8, "e"},  // è latin small letter e with grave
    {0x00E9, "e"},  // é latin small letter e with acute
    {0x00EA, "e"},  // ê latin small letter e with circumflex
    {0x00EB, "e"},  // ë latin small letter e with diaeresis
    {0x00EC, "i"},  // ì latin small letter i with grave
    {0x00ED, "i"},  // í latin small letter i with acute
    {0x00EE, "i"},  // î latin small letter i with circumflex
    {0x00F0, "d"},  // ð latin small letter eth
    {0x00F1, "n"},  // ñ latin small letter n with tilde
    {0x00F2, "o"},  // ò latin small letter o with grave
    {0x00F3, "o"},  // ó latin small letter o with acute
    {0x00F4, "o"},  // ô latin small letter o with circumflex
    {0x00F5, "o"},  // õ latin small letter o with tilde
    {0x00F6, "o"},  // ö latin small letter o with diaeresis
    {0x00F8, "o"},  // ø latin small letter o with stroke
    {0x00F9, "u"},  // ù latin small letter u with grave
    {0x00FA, "u"},  // ú latin small letter u with acute
    {0x00FB, "u"},  // û latin small letter u with circumflex
    {0x00FC, "u"},  // ü latin small letter u with diaeresis
    {0x00FD, "y"},  // ý latin small letter y with acute
    {0x00FE, "th"},  // þ latin small letter thorn
    {0x0100, "a"},  // Ā latin capital letter a with macron
    {0x0101, "a"},  // ā latin small letter a with macron
    {0x0102, "a"},  // Ă latin capital letter a with breve
    {0x0103, "a"},  // ă latin small letter a with breve
    {0x0104, "a"},  // Ą latin capital letter a with ogonek
    {0x0105, "a"},  // ą latin small letter a with ogonek
    {0x0106, "c"},  // Ć latin capital letter c with acute
    {0x0107, "c"},  // ć latin small letter c with acute
    {0x010C, "c"},  // Č latin capital letter c with caron
    {0x010D, "c"},  // č latin small letter c with caron
    {0x010E, "d"},  // Ď latin capital letter d with caron
    {0x010F, "d"},  // ď latin small letter d with caron
    {0x0110, "d"},  // Đ latin capital letter d with stroke
    {0x0111, "d"},  // đ latin small letter d with stroke
    {0x0112, "e"},  // Ē latin capital letter e with macron
    {0x0113, "e"},  // ē latin small letter e with macron
    {0x0116, "e"},  // Ė latin capital letter e with dot above
    {0x0117, "e"},  // ė latin small letter e with dot above
    {0x0118, "e"},  // Ę latin capital letter e with ogonek
    {0x0119, "e"},  // ę latin small letter e with ogonek
    {0x011A, "e"},  // Ě latin capital letter e with caron
    {0x011B, "e"},  // ě latin small letter e with caron
    {0x011E, "g"},  // Ğ latin capital letter g with breve
    {0x011F, "g"},  // ğ latin small letter g with breve
    {0x0122, "g"},  // Ģ latin capital letter g with cedilla
    {0x0123, "g"},  // ģ latin small letter g with cedilla
    {0x012A, "i"},  // Ī latin capital letter i with macron
    {0x012B, "i"},  // ī latin small letter i with macron
    {0x012E, "i"},  // Į latin capital letter i with ogonek
    {0x012F, "i"},  // į latin small letter i with ogonek
    {0x0130, "i"},  // İ latin capital letter i with dot above
    {0x0131, "i"},  // ı latin small letter dotless i
    {0x0136, "k"},  // Ķ latin capital letter k with cedilla
    {0x0137, "k"},  // ķ latin small letter k with cedilla
    {0x013B, "l"},  // Ļ latin capital letter l with cedilla
    {0x013C, "l"},  // ļ latin small letter l with cedilla
    {0x013D, "l"},  // Ľ latin capital letter l with caron
    {0x013E, "l"},  // ľ latin small letter l with caron
    {0x0141, "l"},  // Ł latin capital letter l with stroke
    {0x0142, "l"},  // ł latin small letter l with stroke
    {0x0143, "n"},  // Ń latin capital letter n with acute
    {0x0144, "n"},  // ń latin small letter n with acute
    {0x0145, "n"},  // Ņ latin capital letter n with cedilla
    {0x0146, "n"},  // ņ latin small letter n with cedilla
    {0x0147, "n"},  // Ň latin capital letter n with caron
    {0x0148, "n"},  // ň latin small letter n with caron
    {0x0150, "o"},  // Ő latin capital letter o with double acute
    {0x0151, "o"},  // ő latin small letter o with double acute
    {0x0152, "oe"},  // Œ latin capital ligature oe
    {0x0153, "oe"},  // œ latin small ligature oe
    {0x0158, "r"},  // Ř latin capital letter r with caron
    {0x0159, "r"},  // ř latin small letter r with caron
    {0x015A, "s"},  // Ś latin capital letter s with acute
    {0x015B, "s"},  // ś latin small letter s with acute
    {0x015E, "s"},  // Ş latin capital letter s with cedilla
    {0x015F, "s"},  // ş latin small letter s with cedilla
    {0x0160, "s"},  // Š latin capital letter s with caron
    {0x0161, "s"},  // š latin small letter s with caron
    {0x0164, "t"},  // Ť latin capital letter t with caron
    {0x0165, "t"},  // ť latin small letter t with caron
    {0x016A, "u"},  // Ū latin capital letter u with macron
    {0x016B, "u"},  // ū latin small letter u with macron
    {0x016E, "u"},  // Ů latin capital letter u with ring above
    {0x016F, "u"},  // ů latin small letter u with ring above
    {0x0170, "u"},  // Ű latin capital letter u with double acute
    {0x0171, "u"},  // ű latin small letter u with double acute
    {0x0172, "u"},  // Ų latin capital letter u with ogonek
    {0x0173, "u"},  // ų latin small letter u with ogonek
    {0x0179, "z"},  // Ź latin capital letter z with acute
    {0x017A, "z"},  // ź latin small letter z with acute
    {0x017B, "z"},  // Ż latin capital letter z with dot above
    {0x017C, "z"},  // ż latin small letter z with dot above
    {0x017D, "z"},  // Ž latin capital letter z with caron
    {0x017E, "z"},  // ž latin small letter z with caron
    {0x0218, "s"},  // Ș latin capital letter s with comma below
    {0x0219, "s"},  // ș latin small letter s with comma below
    {0x021A, "t"},  // Ț latin capital letter t with comma below
    {0x021B, "t"},  // ț latin small letter t with comma below
    {0x0386, "a"},  // Ά greek capital letter alpha with tonos
    {0x0388, "e"},  // Έ greek capital letter epsilon with tonos
    {0x0389, "i"},  // Ή greek capital letter eta with tonos
    {0x038A, "i"},  // Ί greek capital letter iota with tonos
    {0x038C, "o"},  // Ό greek capital letter omicron with tonos
    {0x038E, "y"},  // Ύ greek capital letter upsilon with tonos
    {0x038F, "o"},  // Ώ greek capital letter omega with tonos
    {0x0391, "a"},  // Α greek capital letter alpha
    {0x0392, "v"},  // Β greek capital letter beta
    {0x0393, "g"},  // Γ greek capital letter gamma
    {0x0394, "d"},  // Δ greek capital letter delta
    {0x0395, "e"},  // Ε greek capital letter epsilon
    {0x0396, "z"},  // Ζ greek capital letter zeta
    {0x0397, "i"},  // Η greek capital letter eta
    {0x0398, "th"},  // Θ greek capital letter theta
    {0x0399, "i"},  // Ι greek capital letter iota
    {0x039A, "k"},  // Κ greek capital letter kappa
    {0x039B, "l"},  // Λ greek capital letter lamda
    {0x039C, "m"},  // Μ greek capital letter mu
    {0x039D, "n"},  // Ν greek capital letter nu
    {0x039E, "x"},  // Ξ greek capital letter xi
    {0x039F, "o"},  // Ο greek capital letter omicron
    {0x03A0, "p"},  // Π greek capital letter pi
    {0x03A1, "r"},  // Ρ greek capital letter rho
    {0x03A3, "s"},  // Σ greek capital letter sigma
    {0x03A4, "t"},  // Τ greek capital letter tau
    {0x03A5, "y"},  // Υ greek capital letter upsilon
    {0x03A6, "f"},  // Φ greek capital letter phi
    {0x03A7, "ch"},  // Χ greek capital letter chi
    {0x03A8, "ps"},  // Ψ greek capital letter psi
    {0x03A9, "o"},  // Ω greek capital letter omega
    {0x03AC, "a"},  // ά greek small letter alpha with tonos
    {0x03AD, "e"},  // έ greek small letter epsilon with tonos
    {0x03AE, "i"},  // ή greek small letter eta with tonos
    {0x03AF, "i"},  // ί greek small letter iota with tonos
    {0x03B1, "a"},  // α greek small letter alpha
    {0x03B2, "v"},  // β greek small letter beta
    {0x03B3, "g"},  // γ greek small letter gamma
    {0x03B4, "d"},  // δ greek small letter delta
    {0x03B5, "e"},  // ε greek small letter epsilon
    {0x03B6, "z"},  // ζ greek small letter zeta
    {0x03B7, "i"},  // η greek small letter eta
    {0x03B8, "th"},  // θ greek small letter theta
    {0x03B9, "i"},  // ι greek small letter iota
    {0x03BA, "k"},  // κ greek small letter kappa
    {0x03BB, "l"},  // λ greek small letter lamda
    {0x03BC, "m"},  // μ greek small letter mu
    {0x03BD, "n"},  // ν greek small letter nu
    {0x03BE, "x"},  // ξ greek small letter xi
    {0x03BF, "o"},  // ο greek small letter omicron
    {0x03C0, "p"},  // π greek small letter pi
    {0x03C1, "r"},  // ρ greek small letter rho
    {0x03C2, "s"},  // ς greek small letter final sigma
    {0x03C3, "s"},  // σ greek small letter sigma
    {0x03C4, "t"},  // τ greek small letter tau
    {0x03C5, "y"},  // υ greek small letter upsilon
    {0x03C6, "f"},  // φ greek small letter phi
    {0x03C7, "ch"},  // χ greek small letter chi
    {0x03C8, "ps"},  // ψ greek small letter psi
    {0x03C9, "o"},  // ω greek small letter omega
    {0x03CC, "o"},  // ό greek small letter omicron with tonos
    {0x03CD, "y"},  // ύ greek small letter upsilon with tonos
    {0x03CE, "o"},  // ώ greek small letter omega with tonos
    {0x0401, "e"},  // Ё cyrillic capital letter io
    {0x0402, "dj"},  // Ђ cyrillic capital letter dje
    {0x0404, "ye"},  // Є cyrillic capital letter ukrainian ie
    {0x0406, "i"},  // І cyrillic capital letter byelorussian-ukrainian i
    {0x0407, "yi"},  // Ї cyrillic capital letter yi
    {0x0408, "j"},  // Ј cyrillic capital letter je
    {0x0409, "lj"},  // Љ cyrillic capital letter lje
    {0x040A, "nj"},  // Њ cyrillic capital letter nje
    {0x040B, "c"},  // Ћ cyrillic capital letter tshe
    {0x0410, "a"},  // А cyrillic capital letter a
    {0x0411, "b"},  // Б cyrillic capital letter be
    {0x0412, "v"},  // В cyrillic capital letter ve
    {0x0413, "g"},  // Г cyrillic capital letter ghe
    {0x0414, "d"},  // Д cyrillic capital letter de
    {0x0415, "e"},  // Е cyrillic capital letter ie
    {0x0416, "zh"},  // Ж cyrillic capital letter zhe
    {0x0417, "z"},  // З cyrillic capital letter ze
    {0x0418, "i"},  // И cyrillic capital letter i
    {0x0419, "y"},  // Й cyrillic capital letter short i
    {0x041A, "k"},  // К cyrillic capital letter ka
    {0x041B, "l"},  // Л cyrillic capital letter el
    {0x041C, "m"},  // М cyrillic capital letter em
    {0x041D, "n"},  // Н cyrillic capital letter en
    {0x041E, "o"},  // О cyrillic capital letter o
    {0x041F, "p"},  // П cyrillic capital letter pe
    {0x0420, "r"},  // Р cyrillic capital letter er
    {0x0421, "s"},  // С cyrillic capital letter es
    {0x0422, "t"},  // Т cyrillic capital letter te
    {0x0423, "u"},  // У cyrillic capital letter u
    {0x0424, "f"},  // Ф cyrillic capital letter ef
    {0x0425, "h"},  // Х cyrillic capital letter ha
    {0x0426, "ts"},  // Ц cyrillic capital letter tse
    {0x0427, "ch"},  // Ч cyrillic capital letter che
    {0x0428, "sh"},  // Ш cyrillic capital letter sha
    {0x0429, "shch"},  // Щ cyrillic capital letter shcha
    {0x042A, "a"},  // Ъ cyrillic capital letter hard sign
    {0x042B, "y"},  // Ы cyrillic capital letter yeru
    {0x042C, ""},  // Ь cyrillic capital letter soft sign
    {0x042D, "e"},  // Э cyrillic capital letter e
    {0x042E, "yu"},  // Ю cyrillic capital letter yu
    {0x042F, "ya"},  // Я cyrillic capital letter ya
    {0x0430, "a"},  // а cyrillic small letter a
    {0x0431, "b"},  // б cyrillic small letter be
    {0x0432, "v"},  // в cyrillic small letter ve
    {0x0433, "g"},  // г cyrillic small letter ghe
    {0x0434, "d"},  // д cyrillic small letter de
    {0x0435, "e"},  // е cyrillic small letter ie
    {0x0436, "zh"},  // ж cyrillic small letter zhe
    {0x0437, "z"},  // з cyrillic small letter ze
    {0x0438, "i"},  // и cyrillic small letter i
    {0x0439, "y"},  // й cyrillic small letter short i
    {0x043A, "k"},  // к cyrillic small letter ka
    {0x043B, "l"},  // л cyrillic small letter el
    {0x043C, "m"},  // м cyrillic small letter em
    {0x043D, "n"},  // н cyrillic small letter en
    {0x043E, "o"},  // о cyrillic small letter o
    {0x043F, "p"},  // п cyrillic small letter pe
    {0x0440, "r"},  // р cyrillic small letter er
    {0x0441, "s"},  // с cyrillic small letter es
    {0x0442, "t"},  // т cyrillic small letter te
    {0x0443, "u"},  // у cyrillic small letter u
    {0x0444, "f"},  // ф cyrillic small letter ef
    {0x0445, "h"},  // х cyrillic small letter ha
    {0x0446, "ts"},  // ц cyrillic small letter tse
    {0x0447, "ch"},  // ч cyrillic small letter che
    {0x0448, "sh"},  // ш cyrillic small letter sha
    {0x0449, "shch"},  // щ cyrillic small letter shcha
    {0x044A, "a"},  // ъ cyrillic small letter hard sign
    {0x044B, "y"},  // ы cyrillic small letter yeru
    {0x044C, ""},  // ь cyrillic small letter soft sign
    {0x044D, "e"},  // э cyrillic small letter e
    {0x044E, "yu"},  // ю cyrillic small letter yu
    {0x044F, "ya"},  // я cyrillic small letter ya
    {0x0451, "e"},  // ё cyrillic small letter io
    {0x0452, "dj"},  // ђ cyrillic small letter dje
    {0x0454, "ye"},  // є cyrillic small letter ukrainian ie
    {0x0456, "i"},  // і cyrillic small letter byelorussian-ukrainian i
    {0x0457, "yi"},  // ї cyrillic small letter yi
    {0x0458, "j"},  // ј cyrillic small letter je
    {0x0459, "lj"},  // љ cyrillic small letter lje
    {0x045A, "nj"},  // њ cyrillic small letter nje
    {0x045B, "c"},  // ћ cyrillic small letter tshe
    {0x2014, ""},  // — em dash
    {0x201C, ""},  // “ left double quotation mark
    {0x201D, ""},  // ” right double quotation mark
    {0x201E, ""},  // „ double low-9 quotation mark
};
