// GENERATED by tools/make_lang.py from lang/*.txt -- do not edit by hand.
// Edit the text there and run `python3 tools/make_lang.py`; `make check`
// fails if these files are older than the lang files they came from.

// =====================================================================
//  SynthMiner  --  every string the UI can show, and every language
// ---------------------------------------------------------------------
//  One enum for the strings, one for the languages, and a table of
//  pointers per language. A lookup is an array index; there is nothing
//  to parse and nothing to allocate. See i18n.h.
// =====================================================================

#ifndef SM_STRINGS_GEN_H
#define SM_STRINGS_GEN_H

typedef enum {
    SM_STR_MENU_PLAY,                   // menu.play
    SM_STR_MENU_SETTINGS,               // menu.settings
    SM_STR_MENU_QUIT,                   // menu.quit
    SM_STR_WORLDS_TITLE,                // worlds.title
    SM_STR_WORLDS_SLOT,                 // worlds.slot
    SM_STR_WORLDS_SLOT_NEWER,           // worlds.slot_newer
    SM_STR_WORLDS_SLOT_OLDER,           // worlds.slot_older
    SM_STR_WORLDS_SLOT_EMPTY,           // worlds.slot_empty
    SM_STR_WORLDS_DAMAGED,              // worlds.damaged
    SM_STR_WORLD_PLAY,                  // world.play
    SM_STR_WORLD_RENAME,                // world.rename
    SM_STR_WORLD_DELETE,                // world.delete
    SM_STR_WORLD_SUB,                   // world.sub
    SM_STR_NEW_TITLE,                   // new.title
    SM_STR_NEW_SUB,                     // new.sub
    SM_STR_NEW_NAME,                    // new.name
    SM_STR_NEW_SEED,                    // new.seed
    SM_STR_NEW_SEED_RANDOM,             // new.seed_random
    SM_STR_NEW_CREATE,                  // new.create
    SM_STR_NEW_CANCEL,                  // new.cancel
    SM_STR_NEW_DEFAULT_NAME,            // new.default_name
    SM_STR_TEXT_TITLE_RENAME,           // text.title_rename
    SM_STR_TEXT_TITLE_NAME,             // text.title_name
    SM_STR_TEXT_TITLE_SEED,             // text.title_seed
    SM_STR_TEXT_SUB,                    // text.sub
    SM_STR_TEXT_HINT,                   // text.hint
    SM_STR_DELETE_TITLE,                // delete.title
    SM_STR_DELETE_SUB,                  // delete.sub
    SM_STR_DELETE_NO,                   // delete.no
    SM_STR_DELETE_YES,                  // delete.yes
    SM_STR_SETTINGS_TITLE,              // settings.title
    SM_STR_SETTINGS_LANGUAGE,           // settings.language
    SM_STR_SETTINGS_CONTROLS,           // settings.controls
    SM_STR_SETTINGS_GRAPHICS,           // settings.graphics
    SM_STR_SETTINGS_AUDIO,              // settings.audio
    SM_STR_SETTINGS_DISPLAY,            // settings.display
    SM_STR_SETTINGS_LIVESTREAM,         // settings.livestream
    SM_STR_LANGUAGE_TITLE,              // language.title
    SM_STR_CONTROLS_TITLE,              // controls.title
    SM_STR_CONTROLS_GYRO,               // controls.gyro
    SM_STR_CONTROLS_RESET,              // controls.reset
    SM_STR_CONTROLS_HINT,               // controls.hint
    SM_STR_GRAPHICS_TITLE,              // graphics.title
    SM_STR_GRAPHICS_VIEW,               // graphics.view
    SM_STR_GRAPHICS_TEXTURES,           // graphics.textures
    SM_STR_GRAPHICS_RESOLUTION,         // graphics.resolution
    SM_STR_GRAPHICS_CLOUDS,             // graphics.clouds
    SM_STR_GRAPHICS_WATER,              // graphics.water
    SM_STR_GRAPHICS_CAMERA,             // graphics.camera
    SM_STR_GRAPHICS_HAND,               // graphics.hand
    SM_STR_VIEW_NEAR,                   // view.near
    SM_STR_VIEW_MEDIUM,                 // view.medium
    SM_STR_VIEW_FAR,                    // view.far
    SM_STR_RES_HALF,                    // res.half
    SM_STR_RES_FULL,                    // res.full
    SM_STR_CAMERA_FIRST,                // camera.first
    SM_STR_CAMERA_THIRD,                // camera.third
    SM_STR_HAND_LEFT,                   // hand.left
    SM_STR_HAND_RIGHT,                  // hand.right
    SM_STR_AUDIO_TITLE,                 // audio.title
    SM_STR_AUDIO_SUB,                   // audio.sub
    SM_STR_AUDIO_VOLUME,                // audio.volume
    SM_STR_AUDIO_MUSIC,                 // audio.music
    SM_STR_AUDIO_SFX,                   // audio.sfx
    SM_STR_AUDIO_MUSIC_VOLUME,          // audio.music_volume
    SM_STR_AUDIO_SFX_VOLUME,            // audio.sfx_volume
    SM_STR_DISPLAY_TITLE,               // display.title
    SM_STR_DISPLAY_SUB,                 // display.sub
    SM_STR_DISPLAY_SCREEN,              // display.screen
    SM_STR_DISPLAY_KEYBOARD,            // display.keyboard
    SM_STR_DISPLAY_LEDS,                // display.leds
    SM_STR_PAUSE_TITLE,                 // pause.title
    SM_STR_PAUSE_RESUME,                // pause.resume
    SM_STR_PAUSE_SAVE,                  // pause.save
    SM_STR_PAUSE_QUIT,                  // pause.quit
    SM_STR_COMMON_BACK,                 // common.back
    SM_STR_HINT_LIST,                   // hint.list
    SM_STR_HINT_ADJUST,                 // hint.adjust
    SM_STR_STATUS_NEWER,                // status.newer
    SM_STR_STATUS_OLDER,                // status.older
    SM_STR_STATUS_NEEDS_NAME,           // status.needs_name
    SM_STR_STATUS_RENAMED,              // status.renamed
    SM_STR_STATUS_RENAME_FAILED,        // status.rename_failed
    SM_STR_STATUS_DELETED,              // status.deleted
    SM_STR_STATUS_DELETE_FAILED,        // status.delete_failed
    SM_STR_STATUS_KEYS_RESET,           // status.keys_reset
    SM_STR_LOADING_PLAIN,               // loading.plain
    SM_STR_LOADING_WORLD,               // loading.world
    SM_STR_LOADING_CREATING,            // loading.creating
    SM_STR_LOADING_SAVING,              // loading.saving
    SM_STR_HUD_INVENTORY,               // hud.inventory
    SM_STR_HUD_INVENTORY_HINT,          // hud.inventory_hint
    SM_STR_INFO_POSITION,               // info.position
    SM_STR_INFO_FACING,                 // info.facing
    SM_STR_INFO_CLOCK,                  // info.clock
    SM_STR_INFO_DROPPED,                // info.dropped
    SM_STR_INFO_RECORDING,              // info.recording
    SM_STR_INFO_REPLAY,                 // info.replay
    SM_STR_DIR_N,                       // dir.n
    SM_STR_DIR_NE,                      // dir.ne
    SM_STR_DIR_E,                       // dir.e
    SM_STR_DIR_SE,                      // dir.se
    SM_STR_DIR_S,                       // dir.s
    SM_STR_DIR_SW,                      // dir.sw
    SM_STR_DIR_W,                       // dir.w
    SM_STR_DIR_NW,                      // dir.nw
    SM_STR_DIR_N_SHORT,                 // dir.n.short
    SM_STR_DIR_E_SHORT,                 // dir.e.short
    SM_STR_DIR_S_SHORT,                 // dir.s.short
    SM_STR_DIR_W_SHORT,                 // dir.w.short
    SM_STR_SHOT_SAVED,                  // shot.saved
    SM_STR_SHOT_FAILED,                 // shot.failed
    SM_STR_SHOT_FULL,                   // shot.full
    SM_STR_CRAFT_TITLE,                 // craft.title
    SM_STR_CRAFT_TITLE_TABLE,           // craft.title_table
    SM_STR_CRAFT_SEARCH,                // craft.search
    SM_STR_CRAFT_HINT,                  // craft.hint
    SM_STR_CRAFT_EMPTY,                 // craft.empty
    SM_STR_CRAFT_EMPTY_SUB,             // craft.empty_sub
    SM_STR_CRAFT_NO_MATCH,              // craft.no_match
    SM_STR_CRAFT_VALUE_MAKE,            // craft.value_make
    SM_STR_CRAFT_VALUE_MISSING,         // craft.value_missing
    SM_STR_CRAFT_ING,                   // craft.ing
    SM_STR_CRAFT_MADE,                  // craft.made
    SM_STR_CRAFT_FULL,                  // craft.full
    SM_STR_CRAFT_AUTO_ON,               // craft.auto_on
    SM_STR_CRAFT_AUTO_OFF,              // craft.auto_off
    SM_STR_CRAFT_AUTO_MADE,             // craft.auto_made
    SM_STR_CRAFT_DETAIL_SUB,            // craft.detail_sub
    SM_STR_CRAFT_DETAIL_HINT,           // craft.detail_hint
    SM_STR_CRAFT_DETAIL_HAVE,           // craft.detail_have
    SM_STR_ITEM_GRASS,                  // item.grass
    SM_STR_ITEM_DIRT,                   // item.dirt
    SM_STR_ITEM_STONE,                  // item.stone
    SM_STR_ITEM_COBBLESTONE,            // item.cobblestone
    SM_STR_ITEM_SAND,                   // item.sand
    SM_STR_ITEM_WATER,                  // item.water
    SM_STR_ITEM_LOG,                    // item.log
    SM_STR_ITEM_PLANKS,                 // item.planks
    SM_STR_ITEM_LEAVES,                 // item.leaves
    SM_STR_ITEM_COAL_ORE,               // item.coal_ore
    SM_STR_ITEM_GLASS,                  // item.glass
    SM_STR_ITEM_TORCH,                  // item.torch
    SM_STR_ITEM_FLOWER_RED,             // item.flower_red
    SM_STR_ITEM_FLOWER_YELLOW,          // item.flower_yellow
    SM_STR_ITEM_TALL_GRASS,             // item.tall_grass
    SM_STR_ITEM_BEDROCK,                // item.bedrock
    SM_STR_ITEM_GRAVEL,                 // item.gravel
    SM_STR_ITEM_SIGN,                   // item.sign
    SM_STR_ITEM_CRAFTING_TABLE,         // item.crafting_table
    SM_STR_ITEM_FURNACE,                // item.furnace
    SM_STR_ITEM_IRON_ORE,               // item.iron_ore
    SM_STR_ITEM_CHEST,                  // item.chest
    SM_STR_ITEM_TRASH_CHEST,            // item.trash_chest
    SM_STR_ITEM_DISASSEMBLY_BENCH,      // item.disassembly_bench
    SM_STR_ITEM_BIRCH_LOG,              // item.birch_log
    SM_STR_ITEM_BIRCH_LEAVES,           // item.birch_leaves
    SM_STR_ITEM_CACTUS,                 // item.cactus
    SM_STR_ITEM_SNOW,                   // item.snow
    SM_STR_ITEM_SANDSTONE,              // item.sandstone
    SM_STR_ITEM_COAL,                   // item.coal
    SM_STR_ITEM_STICK,                  // item.stick
    SM_STR_ITEM_PICKAXE_WOOD,           // item.pickaxe_wood
    SM_STR_ITEM_PICKAXE_STONE,          // item.pickaxe_stone
    SM_STR_ITEM_AXE_WOOD,               // item.axe_wood
    SM_STR_ITEM_AXE_STONE,              // item.axe_stone
    SM_STR_ITEM_SHOVEL_WOOD,            // item.shovel_wood
    SM_STR_ITEM_SHOVEL_STONE,           // item.shovel_stone
    SM_STR_ITEM_IRON_INGOT,             // item.iron_ingot
    SM_STR_ITEM_PICKAXE_IRON,           // item.pickaxe_iron
    SM_STR_ITEM_AXE_IRON,               // item.axe_iron
    SM_STR_ITEM_SHOVEL_IRON,            // item.shovel_iron
    SM_STR_ITEM_BUCKET,                 // item.bucket
    SM_STR_ITEM_BUCKET_WATER,           // item.bucket_water
    SM_STR_ITEM_HOE_WOOD,               // item.hoe_wood
    SM_STR_ITEM_HOE_STONE,              // item.hoe_stone
    SM_STR_ITEM_HOE_IRON,               // item.hoe_iron
    SM_STR_ITEM_WHEAT_SEEDS,            // item.wheat_seeds
    SM_STR_ITEM_WHEAT,                  // item.wheat
    SM_STR_ITEM_POTATO,                 // item.potato
    SM_STR_ITEM_TOMATO_SEEDS,           // item.tomato_seeds
    SM_STR_ITEM_TOMATO,                 // item.tomato
    SM_STR_ITEM_BEANS,                  // item.beans
    SM_STR_ITEM_RICE,                   // item.rice
    SM_STR_ITEM_COMPOST,                // item.compost
    SM_STR_ITEM_WORM,                   // item.worm
    SM_STR_ITEM_PORK,                   // item.pork
    SM_STR_ITEM_BEEF,                   // item.beef
    SM_STR_ITEM_BUCKET_MILK,            // item.bucket_milk
    SM_STR_ITEM_CHEESE,                 // item.cheese
    SM_STR_ITEM_SAUSAGE,                // item.sausage
    SM_STR_ITEM_SAUSAGE_VEG,            // item.sausage_veg
    SM_STR_ITEM_BONE,                   // item.bone
    SM_STR_ITEM_MUTTON,                 // item.mutton
    SM_STR_ITEM_WOOL,                   // item.wool
    SM_STR_ITEM_SHEARS,                 // item.shears
    SM_STR_ITEM_STRING,                 // item.string
    SM_STR_ITEM_MUTTON_MASH,            // item.mutton_mash
    SM_STR_ITEM_KEBAB,                  // item.kebab
    SM_STR_ITEM_FISHING_ROD,            // item.fishing_rod
    SM_STR_ITEM_SARDINE,                // item.sardine
    SM_STR_ITEM_SALMON,                 // item.salmon
    SM_STR_ITEM_SHRIMP,                 // item.shrimp
    SM_STR_ITEM_BAKED_POTATO,           // item.baked_potato
    SM_STR_ITEM_GRILLED_TOMATOES,       // item.grilled_tomatoes
    SM_STR_ITEM_BAKED_BEANS,            // item.baked_beans
    SM_STR_ITEM_BREAD,                  // item.bread
    SM_STR_ITEM_RICE_PATTY,             // item.rice_patty
    SM_STR_ITEM_SMOKED_SALMON,          // item.smoked_salmon
    SM_STR_ITEM_GRILLED_SHRIMP,         // item.grilled_shrimp
    SM_STR_ITEM_SASHIMI,                // item.sashimi
    SM_STR_ITEM_PORK_AND_BEANS,         // item.pork_and_beans
    SM_STR_ITEM_STEAK_AND_POTATOES,     // item.steak_and_potatoes
    SM_STR_ITEM_PIZZA,                  // item.pizza
    SM_STR_ITEM_FARMLAND,               // item.farmland
    SM_STR_ITEM_COMPOSTER,              // item.composter
    SM_STR_ITEM_CHEESE_MAKER,           // item.cheese_maker
    SM_STR_ITEM_SAUSAGE_MAKER,          // item.sausage_maker
    SM_STR_ITEM_FENCE,                  // item.fence
    SM_STR_ITEM_FENCE_GATE,             // item.fence_gate
    SM_STR_ITEM_BED_FOOT,               // item.bed_foot
    SM_STR_ITEM_STOVE,                  // item.stove
    SM_STR_ITEM_SAPLING_OAK,            // item.sapling_oak
    SM_STR_ITEM_SAPLING_BIRCH,          // item.sapling_birch
    SM_STR_ITEM_WHEAT_CROP,             // item.wheat_crop
    SM_STR_ITEM_POTATO_CROP,            // item.potato_crop
    SM_STR_ITEM_TOMATO_CROP,            // item.tomato_crop
    SM_STR_ITEM_BEAN_CROP,              // item.bean_crop
    SM_STR_ITEM_RICE_CROP,              // item.rice_crop
    SM_STR_FURNACE_TITLE,               // furnace.title
    SM_STR_FURNACE_INPUT,               // furnace.input
    SM_STR_FURNACE_FUEL,                // furnace.fuel
    SM_STR_FURNACE_OUTPUT,              // furnace.output
    SM_STR_FURNACE_EMPTY,               // furnace.empty
    SM_STR_FURNACE_SLOT,                // furnace.slot
    SM_STR_FURNACE_HINT,                // furnace.hint
    SM_STR_FURNACE_SMELTING,            // furnace.smelting
    SM_STR_FURNACE_NO_INPUT,            // furnace.no_input
    SM_STR_FURNACE_NO_FUEL,             // furnace.no_fuel
    SM_STR_FURNACE_FULL,                // furnace.full
    SM_STR_FURNACE_TOOK,                // furnace.took
    SM_STR_FURNACE_PICK_INPUT,          // furnace.pick_input
    SM_STR_FURNACE_PICK_FUEL,           // furnace.pick_fuel
    SM_STR_FURNACE_PICK_NONE_INPUT,     // furnace.pick_none_input
    SM_STR_FURNACE_PICK_NONE_FUEL,      // furnace.pick_none_fuel
    SM_STR_FURNACE_PICK_HINT,           // furnace.pick_hint
    SM_STR_FURNACE_BECOMES,             // furnace.becomes
    SM_STR_FURNACE_BURNS,               // furnace.burns
    SM_STR_CHEST_TITLE,                 // chest.title
    SM_STR_CHEST_TITLE_TRASH,           // chest.title_trash
    SM_STR_CHEST_YOURS,                 // chest.yours
    SM_STR_CHEST_HINT,                  // chest.hint
    SM_STR_CHEST_NO_ROOM,               // chest.no_room
    SM_STR_CHEST_TRASH_WARN,            // chest.trash_warn
    SM_STR_CHEST_TRASH_GONE,            // chest.trash_gone
    SM_STR_AMOUNT_TITLE,                // amount.title
    SM_STR_AMOUNT_HINT,                 // amount.hint
    SM_STR_BENCH_TITLE,                 // bench.title
    SM_STR_BENCH_HINT,                  // bench.hint
    SM_STR_BENCH_EMPTY,                 // bench.empty
    SM_STR_BENCH_GIVES,                 // bench.gives
    SM_STR_BENCH_DONE,                  // bench.done
    SM_STR_COMPOSTER_TITLE,             // composter.title
    SM_STR_COMPOSTER_INPUT,             // composter.input
    SM_STR_COMPOSTER_COMPOST,           // composter.compost
    SM_STR_COMPOSTER_WORMS,             // composter.worms
    SM_STR_COMPOSTER_EMPTY,             // composter.empty
    SM_STR_COMPOSTER_SLOT,              // composter.slot
    SM_STR_COMPOSTER_HINT,              // composter.hint
    SM_STR_COMPOSTER_WORKING,           // composter.working
    SM_STR_COMPOSTER_NO_INPUT,          // composter.no_input
    SM_STR_COMPOSTER_FULL,              // composter.full
    SM_STR_COMPOSTER_TOOK,              // composter.took
    SM_STR_COMPOSTER_PICK_INPUT,        // composter.pick_input
    SM_STR_COMPOSTER_PICK_NONE,         // composter.pick_none
    SM_STR_COMPOSTER_PICK_HINT,         // composter.pick_hint
    SM_STR_COMPOSTER_A_DAY,             // composter.a_day
    SM_STR_FARM_CANNOT_TILL,            // farm.cannot_till
    SM_STR_FARM_TOO_DRY,                // farm.too_dry
    SM_STR_FARM_NEEDS_SOIL,             // farm.needs_soil
    SM_STR_FARM_NEEDS_WATER,            // farm.needs_water
    SM_STR_FARM_NEEDS_GROUND,           // farm.needs_ground
    SM_STR_FARM_ALREADY_RIPE,           // farm.already_ripe
    SM_STR_MOB_PIG,                     // mob.pig
    SM_STR_MOB_COW,                     // mob.cow
    SM_STR_MOB_DOG,                     // mob.dog
    SM_STR_MOB_SHEEP,                   // mob.sheep
    SM_STR_MOB_READY,                   // mob.ready
    SM_STR_MOB_YOUNG,                   // mob.young
    SM_STR_MOB_RESTING,                 // mob.resting
    SM_STR_ANIMAL_MILKED,               // animal.milked
    SM_STR_ANIMAL_FED,                  // animal.fed
    SM_STR_ANIMAL_TAMED,                // animal.tamed
    SM_STR_ANIMAL_BUSY,                 // animal.busy
    SM_STR_ANIMAL_SHORN,                // animal.shorn
    SM_STR_ANIMAL_BARE,                 // animal.bare
    SM_STR_ANIMAL_SITS,                 // animal.sits
    SM_STR_ANIMAL_STANDS,               // animal.stands
    SM_STR_MAKER_CHEESE_TITLE,          // maker.cheese_title
    SM_STR_MAKER_SAUSAGE_TITLE,         // maker.sausage_title
    SM_STR_MAKER_INPUT,                 // maker.input
    SM_STR_MAKER_OUTPUT,                // maker.output
    SM_STR_MAKER_EXTRA,                 // maker.extra
    SM_STR_MAKER_EMPTY,                 // maker.empty
    SM_STR_MAKER_SLOT,                  // maker.slot
    SM_STR_MAKER_HINT,                  // maker.hint
    SM_STR_MAKER_WORKING,               // maker.working
    SM_STR_MAKER_NO_INPUT,              // maker.no_input
    SM_STR_MAKER_FULL,                  // maker.full
    SM_STR_MAKER_TOOK,                  // maker.took
    SM_STR_MAKER_TAKE_OUT,              // maker.take_out
    SM_STR_MAKER_MISSING,               // maker.missing
    SM_STR_MAKER_OR,                    // maker.or
    SM_STR_MAKER_PICK_INPUT,            // maker.pick_input
    SM_STR_MAKER_PICK_NONE,             // maker.pick_none
    SM_STR_MAKER_PICK_HINT,             // maker.pick_hint
    SM_STR_MAKER_A_DAY,                 // maker.a_day
    SM_STR_MAKER_A_MINUTE,              // maker.a_minute
    SM_STR_MAKER_BUCKET_BACK,           // maker.bucket_back
    SM_STR_STOVE_TITLE,                 // stove.title
    SM_STR_STOVE_DISH,                  // stove.dish
    SM_STR_STOVE_FUEL,                  // stove.fuel
    SM_STR_STOVE_OUTPUT,                // stove.output
    SM_STR_STOVE_EMPTY,                 // stove.empty
    SM_STR_STOVE_NONE,                  // stove.none
    SM_STR_STOVE_SLOT,                  // stove.slot
    SM_STR_STOVE_HINT,                  // stove.hint
    SM_STR_STOVE_COOKING,               // stove.cooking
    SM_STR_STOVE_NO_PICK,               // stove.no_pick
    SM_STR_STOVE_NO_CHEST,              // stove.no_chest
    SM_STR_STOVE_MISSING,               // stove.missing
    SM_STR_STOVE_NO_FUEL,               // stove.no_fuel
    SM_STR_STOVE_FULL,                  // stove.full
    SM_STR_STOVE_TOOK,                  // stove.took
    SM_STR_STOVE_PICK_TITLE,            // stove.pick_title
    SM_STR_STOVE_PICK_HINT,             // stove.pick_hint
    SM_STR_STOVE_PICK_FUEL,             // stove.pick_fuel
    SM_STR_STOVE_PICK_NONE_FUEL,        // stove.pick_none_fuel
    SM_STR_STOVE_NEEDS,                 // stove.needs
    SM_STR_STOVE_FEEDS,                 // stove.feeds
    SM_STR_STOVE_FROM_CHEST,            // stove.from_chest
    SM_STR_FOOD_NOT_HUNGRY,             // food.not_hungry
    SM_STR_FOOD_STARVING,               // food.starving
    SM_STR_FOOD_DIED,                   // food.died
    SM_STR_FOOD_RESPAWN,                // food.respawn
    SM_STR_FISH_CAST,                   // fish.cast
    SM_STR_FISH_NO_WORM,                // fish.no_worm
    SM_STR_FISH_NO_WATER,               // fish.no_water
    SM_STR_FISH_CAUGHT,                 // fish.caught
    SM_STR_FISH_TOO_SOON,               // fish.too_soon
    SM_STR_FISH_REELED,                 // fish.reeled
    SM_STR_BED_SLEPT,                   // bed.slept
    SM_STR_BED_DAYTIME,                 // bed.daytime
    SM_STR_BED_NO_ROOM,                 // bed.no_room
    SM_STR_BED_SPAWN_SET,               // bed.spawn_set
    SM_STR_HUD_NEEDS_TOOL,              // hud.needs_tool
    SM_STR_ACTION_FORWARD,              // action.forward
    SM_STR_ACTION_BACK,                 // action.back
    SM_STR_ACTION_LEFT,                 // action.left
    SM_STR_ACTION_RIGHT,                // action.right
    SM_STR_ACTION_JUMP,                 // action.jump
    SM_STR_ACTION_SNEAK,                // action.sneak
    SM_STR_ACTION_ATTACK,               // action.attack
    SM_STR_ACTION_USE,                  // action.use
    SM_STR_ACTION_LOOKUP,               // action.lookup
    SM_STR_ACTION_LOOKDOWN,             // action.lookdown
    SM_STR_ACTION_LOOKLEFT,             // action.lookleft
    SM_STR_ACTION_LOOKRIGHT,            // action.lookright
    SM_STR_ACTION_SLOT1,                // action.slot1
    SM_STR_ACTION_SLOT2,                // action.slot2
    SM_STR_ACTION_SLOT3,                // action.slot3
    SM_STR_ACTION_SLOT4,                // action.slot4
    SM_STR_ACTION_SLOT5,                // action.slot5
    SM_STR_ACTION_SLOT6,                // action.slot6
    SM_STR_ACTION_INV,                  // action.inv
    SM_STR_ACTION_PAUSE,                // action.pause
    SM_STR_ACTION_DROP,                 // action.drop
    SM_STR_ACTION_INFO,                 // action.info
    SM_STR_ACTION_SCREENSHOT,           // action.screenshot
    SM_STR_ACTION_CRAFT,                // action.craft
    SM_STR_COUNT
} sm_str_t;

typedef enum {
    SM_LANG_EN,       // en     English
    SM_LANG_CA,       // ca     Català
    SM_LANG_CS,       // cs     Čeština
    SM_LANG_DA,       // da     Dansk
    SM_LANG_DE,       // de     Deutsch
    SM_LANG_ET,       // et     Eesti
    SM_LANG_ES,       // es     Español
    SM_LANG_FR,       // fr     Français
    SM_LANG_GA,       // ga     Gaeilge
    SM_LANG_HR,       // hr     Hrvatski
    SM_LANG_IS,       // is     Íslenska
    SM_LANG_IT,       // it     Italiano
    SM_LANG_LV,       // lv     Latviešu
    SM_LANG_LT,       // lt     Lietuvių
    SM_LANG_HU,       // hu     Magyar
    SM_LANG_NL,       // nl     Nederlands
    SM_LANG_NO,       // no     Norsk
    SM_LANG_PL,       // pl     Polski
    SM_LANG_PT,       // pt     Português
    SM_LANG_RO,       // ro     Română
    SM_LANG_SQ,       // sq     Shqip
    SM_LANG_SK,       // sk     Slovenčina
    SM_LANG_SL,       // sl     Slovenščina
    SM_LANG_FI,       // fi     Suomi
    SM_LANG_SV,       // sv     Svenska
    SM_LANG_TR,       // tr     Türkçe
    SM_LANG_NL_BE,    // nl-BE  Vlaams
    SM_LANG_EL,       // el     Ελληνικά
    SM_LANG_BG,       // bg     Български
    SM_LANG_RU,       // ru     Русский
    SM_LANG_SR,       // sr     Српски
    SM_LANG_UK,       // uk     Українська
    SM_LANG_COUNT
} sm_lang_t;

// [language][string]. Full for every language: a translation that
// does not have a string was given the English one when this was
// generated, so nothing has to fall back at run time.
extern char const* const SM_STRINGS[SM_LANG_COUNT][SM_STR_COUNT];
extern char const* const SM_LANG_CODES[SM_LANG_COUNT];
extern char const* const SM_LANG_NAMES[SM_LANG_COUNT];
// The key each string is known by in lang/*.txt, for the override
// files a player may put on the SD card (i18n_load_overrides).
extern char const* const SM_STR_KEYS[SM_STR_COUNT];

#endif  // SM_STRINGS_GEN_H
